### PR TITLE
Implement difference-of-squares

### PR DESCRIPTION
**Pull request by m-dango**

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by m-dango** [comment]
Thanks, @habere-et-dispertire, although this PR already has a solution (which is funnily enough, completely identical to yours!)

**Comment by habere-et-dispertire** [comment]
Thanks @m-dango and no problem --- I don't grok GitHub. The solution stills looks empty to me in this thread, even after refresh. What am I not getting?

[Screenshot attached](https://user-images.githubusercontent.com/18032974/178051800-fd509b6a-4de2-4df7-b889-4799f8020269.png).

**Comment by habere-et-dispertire** [comment]
It looks like there is an empty stub solution file, and I should have been looking in the solutions folder.

**Comment by m-dango** [comment]
@habere-et-dispertire there are two copies of the module, the main one is the stub code that people receive when they start the exercise on the site. The solved copy lives in the `.meta/solutions` directory which we use for testing the exercise functions correctly.

**Comment by habere-et-dispertire** [comment]
Thank you that was helpful. I just somehow blanked on making that association, thank you for spelling it out. :)

**Pull request merged**
