### PR TITLE
Set singular enum name for allergies

### PR DESCRIPTION
**Pull request by m-dango**
Enum names are usually singular

### CODE REVIEW

**Comment by kotp** [comment]
At what cost? The plural is plural for a collection of 0 or more, while singular is usually reserved for one and only one.  In language, I mean, as in describing the problem being solved, rather than the Stroop Effect that is here perhaps drawing us down to the language of the program itself.  Where do you want the language to focus, the problem or the language?

I do not care strongly to make it "suitable as a name for Enums" when the constant is really describing a collection of 0 or more allergens.

I would also not fight too hard to make it indicate the type, if that is really what we are doing here... depends on where we want to focus the story when we read the code.

**Review by kotp — APPROVED** [review]
Approving, with the comment posted with my gentle suggestion to have the language more strongly describe the problem being solved, rather than strongly describing the underlying programming language being used.

**Comment by m-dango** [comment]
I want to keep consistency with the valentines-day exercise which introduces types. `enum Allergen ...` is not just a collection, but introduces a type which can be optionally used. Examples include for coercion `my Allergen(Int) $item = 32` and the use of methods:

```
# Allergen:D: means the method can only be called on a defined Allergen object
Allergen.^add_method('allergic-to', method ( Allergen:D: UInt:D $score --> Bool:D ) {
    so self +& $score;
});

allergic-to Chocolate: $score;

**Comment by kotp** [comment]
Sounds good.  It is good to have the reasoning recorded and available somewhere.

**Pull request merged**
